// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybafrqbmayanwsfhgrvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliYWZycWJtYXlhbndzZmhncnZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjAxMTksImV4cCI6MjA2NDYzNjExOX0.KZdvbG8NW9CMKldcv_pK7-tICLScnbcixh0k0efeCNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);